### ISSUE TITLE
问题，请协助，测试高可用出现的问题。

### ISSUE THREAD

**Issue by linuxvip** [xiaoping378/k8s-deploy#1]
## 首先感谢您写的一键部署脚本，方便了我的部署，非常感谢。
在此我提俩个小问题，关于一键部署k8s 1.5的脚本。

### 问题1：
在使用一键部署脚本的时候，在脚本中匹配 网卡设备名称的一段，写的不是很严谨，因为我的IP是动态DHCP获取，所以脚本中getenv段，出现了匹配网卡设备出现了一点点小bug。

### 问题2：
①在使用脚本完成了k8s环境的部署，我来模拟集群的主master01 故障，我手动关闭master01的keepalive，来模拟master01故障，VIP进行了漂移，当然这是没有问题的。VIP漂移到了master02，但是在master02上执行get node命令。看到master01 显示Not Ready。我感觉这是不应该的。

②然后我手动启动了master01的keepalived，来模拟master01恢复，master01 立刻就抢占了VIP，这不是预期的效果，然而在master 01上执行get node命令，master01依旧显示 Not Ready，这是我不能理解的。

③我在master01上直接进行了关机操作，真正模拟master01 断电断网故障，VIP漂移至master02，开机启动master01，来恢复master01，此时vip不进行漂移（说明master01没有抢占），但是master01 服务正常后，需要等待一段时间（10分钟左右）才能显示Ready~

我的问题表述完毕，请帮忙协助！多谢！

**Comment by xiaoping378** [comment]
Thanks，我会定位下：
1. 增加适配范围，static IP and DHCP IP.
2. stop keepalived, get node不该出现NotReady.

**Comment by xiaoping378** [comment]
第二个问题是长连接导致的，可以算是问题，也可以不算，对最终HA影响不大，问题关闭了哦
