### ISSUE TITLE
删除集群问题

### ISSUE THREAD

**Issue by post707** [xiaoping378/k8s-deploy#3]
在使脚本删除程序时候，网络信息删除不干净，再重新使用脚本安装集群的时候启动flannel容器失败，一直启动不了~？具体原因没有找到

**Comment by aking666** [comment]
@post707  有安装过程中的日志和flannel容器启动失败的日记吗？

在我的环境里，删除minion节点后，再次装的时候会提示 “Node with name ["XXX"] already exists.”。
解决方法：需要在master上执行 kubectl delete node XXX，然后再装就可以了。
不知道跟你碰到的是不是一个问题。

**Comment by post707** [comment]
close
