### ISSUE TITLE
couldn't parse external etcd version "": Version string empty

### ISSUE THREAD

**Issue by Delacroix** [xiaoping378/k8s-deploy#7]
您好，我在部署的过程中，出现以下报错，可能是什么原因导致的呢？

> + kubeadm init --config=/root/kubeadm-config.yml
> [kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
> [init] Using Kubernetes version: v1.6.2
> [init] Using Authorization mode: RBAC
> [preflight] Running pre-flight checks
> [preflight] Some fatal errors occurred:
> 	couldn't parse external etcd version "": Version string empty
> 	couldn't parse external etcd version "": Version string empty
> 	couldn't parse external etcd version "": Version string empty
> [preflight] If you know what you are doing, you can skip pre-flight checks with `--skip-preflight-checks

`

**Comment by xiaoping378** [comment]
HI，你的master可以访问到你的etcd集群么, 错误日志显示找不到你的etcd集群

如果没有etcd集群的话，可以用etcd目录的脚本一键安装

**Comment by xrxgrape** [comment]
我也遇到这个问题，是没有认真看readme中的说明 ：P   // “部署HA环境，需要先存在etcd集群，可使用etcd目录下的一键部署etcd集群脚本”

但是我用etcd目录的脚本一键安装etcd集群，安装了多次，发现每次都是其中2个节点部署成功，最后部署的那个节点unreachable: no available published client urls。
暂时还没有找到原因。
