### ISSUE TITLE
求添加kubernetes-dashboard

### ISSUE THREAD

**Issue by yuananf** [xiaoping378/k8s-deploy#9]
如题
或者讲解下如何自己打包kubernetes-dashboard的docker tar包，我自己打的tar包在创建dashboard的时候总是报错{"message":"No command specified"}
谢谢！

**Comment by itxx00** [comment]
@yuananf  可以参考一下https://github.com/5xops/k8s-deploy/commit/1766a675d76edb32f310acd98d5c6ed50a356e5b
镜像可以在这里找到https://hub.docker.com/r/googlecontainer/kubernetes-dashboard-amd64/
